import QEC1.Definitions.Def_1_StabilizerCode
import QEC1.Definitions.Def_19_CSSCode

/-!
# Subsystem Code (Definition 20)

## Statement
A **subsystem code** is a generalization of a stabilizer code where the code space factors as:
  C = C_logical ⊗ C_gauge

**Components**:
- **Gauge group** G: A (generally non-abelian) subgroup of the Pauli group
- **Stabilizer group** S = Z(G) ∩ G: The center of the gauge group intersected with itself (abelian)
- **Code space**: Simultaneous +1 eigenspace of all stabilizers in S
- **Gauge qubits**: Degrees of freedom in C_gauge, not used for logical information

**Gauge fixing**: A subsystem code can be converted to a stabilizer code by measuring
gauge operators, collapsing C_gauge to a definite state.

The deformed code after gauging is a subsystem code when |E| > |V| - 1,
with gauge degrees of freedom on the edge qubits.

## Main Results
**Main Structure** (`SubsystemCode`): Complete subsystem code specification
- `gaugeGenerators`: Generators of the gauge group
- `stabilizerGenerators`: Generators of the stabilizer subgroup (center elements)
- Properties ensuring the center relationship and commutation

## File Structure
1. Gauge Operator: Pauli operators generating the gauge group
2. Stabilizer Subgroup: Center of gauge group (commuting subset)
3. Subsystem Code Structure: Full subsystem code definition
4. Gauge Fixing: Converting to stabilizer code
5. Deformed Code Condition: When |E| > |V| - 1
6. Helper Lemmas: Basic properties
-/

namespace QEC

/-! ## Section 1: Gauge Operator -/

/-- A gauge operator is a Pauli operator (same representation as StabilizerCheck).
    In a subsystem code, gauge operators form a (generally non-abelian) group. -/
abbrev GaugeOperator (n : ℕ) := StabilizerCheck n

namespace GaugeOperator

variable {n : ℕ}

/-- The identity gauge operator -/
def identity (n : ℕ) : GaugeOperator n := StabilizerCheck.identity n

/-- Two gauge operators commute if their symplectic product is even -/
def commutes (g₁ g₂ : GaugeOperator n) : Prop := StabilizerCheck.commutes g₁ g₂

/-- Product of two gauge operators -/
def mul (g₁ g₂ : GaugeOperator n) : GaugeOperator n := StabilizerCheck.mul g₁ g₂

/-- Weight of a gauge operator -/
def weight (g : GaugeOperator n) : ℕ := StabilizerCheck.weight g

/-- Commutation is symmetric -/
theorem commutes_symm (g₁ g₂ : GaugeOperator n) :
    commutes g₁ g₂ ↔ commutes g₂ g₁ := StabilizerCheck.commutes_symm g₁ g₂

/-- Every operator commutes with itself -/
theorem self_commutes (g : GaugeOperator n) : commutes g g := StabilizerCheck.self_commutes g

/-- Identity commutes with everything -/
theorem identity_commutes (g : GaugeOperator n) : commutes (identity n) g :=
  StabilizerCheck.identity_commutes_all g

end GaugeOperator

/-! ## Section 2: Stabilizer Subgroup from Gauge Group -/

/-- A gauge operator is in the center of a gauge group if it commutes with all generators.
    The stabilizer group S = Z(G) ∩ G consists of exactly these center elements. -/
def isInCenter {n m : ℕ} (gaugeGenerators : Fin m → GaugeOperator n)
    (g : GaugeOperator n) : Prop :=
  ∀ i, GaugeOperator.commutes g (gaugeGenerators i)

/-- Center elements are closed under multiplication -/
theorem center_mul_closed {n m : ℕ} (gaugeGenerators : Fin m → GaugeOperator n)
    (g₁ g₂ : GaugeOperator n) (h₁ : isInCenter gaugeGenerators g₁)
    (h₂ : isInCenter gaugeGenerators g₂) :
    isInCenter gaugeGenerators (GaugeOperator.mul g₁ g₂) := by
  intro i
  unfold GaugeOperator.commutes GaugeOperator.mul
  exact mul_commutes_of_commutes g₁ g₂ (gaugeGenerators i) (h₁ i) (h₂ i)

/-- Identity is always in the center -/
theorem identity_in_center {n m : ℕ} (gaugeGenerators : Fin m → GaugeOperator n) :
    isInCenter gaugeGenerators (GaugeOperator.identity n) := by
  intro i
  exact GaugeOperator.identity_commutes _

/-! ## Section 3: Subsystem Code Structure -/

/-- A subsystem code on n qubits.
    Parameters:
    - n: number of physical qubits
    - mGauge: number of gauge generators
    - mStab: number of stabilizer generators (subset of gauge that commute with all gauge)

    The gauge group G is generated by gauge operators.
    The stabilizer group S = Z(G) ∩ G is the center of G (abelian).
    The code space is the +1 eigenspace of all stabilizers.
    Gauge qubits are additional degrees of freedom not used for logical information. -/
structure SubsystemCode (n mGauge mStab : ℕ) where
  /-- Generators of the gauge group G -/
  gaugeGenerators : Fin mGauge → GaugeOperator n
  /-- Generators of the stabilizer group S ⊆ Z(G) -/
  stabilizerGenerators : Fin mStab → GaugeOperator n
  /-- Each stabilizer generator is in the center of the gauge group -/
  stabilizers_in_center : ∀ j, isInCenter gaugeGenerators (stabilizerGenerators j)
  /-- Stabilizers mutually commute (follows from being in center, but explicit) -/
  stabilizers_commute :
    ∀ i j, GaugeOperator.commutes (stabilizerGenerators i) (stabilizerGenerators j)

namespace SubsystemCode

variable {n mGauge mStab : ℕ}

/-- Number of physical qubits -/
def numQubits (_C : SubsystemCode n mGauge mStab) : ℕ := n

/-- Number of gauge generators -/
def numGaugeGenerators (_C : SubsystemCode n mGauge mStab) : ℕ := mGauge

/-- Number of stabilizer generators -/
def numStabilizerGenerators (_C : SubsystemCode n mGauge mStab) : ℕ := mStab

/-- Get a gauge generator -/
def getGaugeGenerator (C : SubsystemCode n mGauge mStab) (i : Fin mGauge) : GaugeOperator n :=
  C.gaugeGenerators i

/-- Get a stabilizer generator -/
def getStabilizerGenerator (C : SubsystemCode n mGauge mStab) (j : Fin mStab) : GaugeOperator n :=
  C.stabilizerGenerators j

/-- Stabilizer generators commute with all gauge generators -/
theorem stabilizer_commutes_gauge (C : SubsystemCode n mGauge mStab)
    (j : Fin mStab) (i : Fin mGauge) :
    GaugeOperator.commutes (C.stabilizerGenerators j) (C.gaugeGenerators i) :=
  C.stabilizers_in_center j i

/-- Two arbitrary stabilizers commute -/
theorem stabilizer_pair_commutes (C : SubsystemCode n mGauge mStab)
    (j₁ j₂ : Fin mStab) :
    GaugeOperator.commutes (C.stabilizerGenerators j₁) (C.stabilizerGenerators j₂) :=
  C.stabilizers_commute j₁ j₂

end SubsystemCode

/-! ## Section 4: Gauge Fixing -/

/-- Gauge fixing data: a choice of measurement outcomes for gauge qubits.
    When we measure gauge operators, we collapse C_gauge to a definite state,
    converting the subsystem code to a stabilizer code. -/
structure GaugeFixing (n mGauge mStab : ℕ) where
  /-- The subsystem code being fixed -/
  code : SubsystemCode n mGauge mStab
  /-- Measurement outcomes for "independent" gauge operators (those not in stabilizer) -/
  outcomes : Fin (mGauge - mStab) → Bool

/-- The number of gauge qubits (degrees of freedom in C_gauge).
    This equals (mGauge - mStab) / 2 when all gauge operators pair up properly. -/
def numGaugeQubits (_n mGauge mStab : ℕ) : ℕ := (mGauge - mStab) / 2

/-- After gauge fixing, the effective number of stabilizer generators increases -/
def effectiveStabilizers {n mGauge mStab : ℕ} (_gf : GaugeFixing n mGauge mStab) : ℕ := mGauge

/-! ## Section 5: Code Space Factorization -/

/-- The code space dimension of a subsystem code.
    dim(C) = 2^k where k accounts for both logical and gauge qubits.
    We have C = C_logical ⊗ C_gauge with dimensions 2^k_L ⊗ 2^k_G. -/
def codespaceDimExponent (n _mGauge mStab : ℕ) : ℕ :=
  n - mStab

/-- Logical qubit dimension exponent -/
def logicalDimExponent (n mGauge _mStab : ℕ) : ℕ :=
  n - mGauge

/-- Gauge qubit dimension exponent -/
def gaugeDimExponent (mGauge mStab : ℕ) : ℕ :=
  (mGauge - mStab) / 2

/-- Total dimension is product: dim(C) = dim(C_logical) × dim(C_gauge) -/
theorem codespace_factorization (n mGauge mStab : ℕ)
    (h_stab_le_gauge : mStab ≤ mGauge)
    (h_gauge_le_n : mGauge ≤ n) :
    codespaceDimExponent n mGauge mStab =
    logicalDimExponent n mGauge mStab + (mGauge - mStab) := by
  simp only [codespaceDimExponent, logicalDimExponent]
  omega

/-! ## Section 6: Deformed Code Condition -/

/-- The condition for a deformed code to be a subsystem code: |E| > |V| - 1.
    Parameters:
    - numEdges: number of edges |E| in the gauging graph
    - numVertices: number of vertices |V| in the gauging graph

    When this holds, there are gauge degrees of freedom on the edge qubits. -/
structure DeformedCodeSubsystemCondition where
  /-- Number of edges in the gauging graph -/
  numEdges : ℕ
  /-- Number of vertices in the gauging graph -/
  numVertices : ℕ
  /-- The condition |E| > |V| - 1 -/
  edge_vertex_condition : numEdges > numVertices - 1

namespace DeformedCodeSubsystemCondition

/-- Number of gauge degrees of freedom from edge qubits -/
def numEdgeGaugeQubits (cond : DeformedCodeSubsystemCondition) : ℕ :=
  cond.numEdges - (cond.numVertices - 1)

/-- The gauge degrees of freedom are positive when condition holds -/
theorem edge_gauge_qubits_pos (cond : DeformedCodeSubsystemCondition) :
    cond.numEdgeGaugeQubits ≥ 1 := by
  unfold numEdgeGaugeQubits
  have h := cond.edge_vertex_condition
  omega

/-- Alternative formulation: |E| ≥ |V| -/
theorem edge_ge_vertex (cond : DeformedCodeSubsystemCondition) :
    cond.numEdges ≥ cond.numVertices := by
  have h := cond.edge_vertex_condition
  omega

end DeformedCodeSubsystemCondition

/-! ## Section 7: Conversion Between Code Types -/

/-- A stabilizer code can be viewed as a subsystem code with no gauge qubits.
    All generators are stabilizers (in the center). -/
def stabilizerToSubsystem {n k : ℕ} (C : StabilizerCode n k) :
    SubsystemCode n (n - k) (n - k) where
  gaugeGenerators := C.checks
  stabilizerGenerators := C.checks
  stabilizers_in_center := fun j i => C.checks_commute j i
  stabilizers_commute := C.checks_commute

/-- When mGauge = mStab, the subsystem code is effectively a stabilizer code -/
def isEffectivelyStabilizer {n mGauge mStab : ℕ}
    (_C : SubsystemCode n mGauge mStab) : Prop :=
  mGauge = mStab

/-- Gauge dimension is zero when subsystem code is effectively a stabilizer code -/
theorem gauge_dim_zero_of_effectively_stabilizer {n m : ℕ}
    (_C : SubsystemCode n m m) :
    gaugeDimExponent m m = 0 := by
  simp only [gaugeDimExponent, Nat.sub_self, Nat.zero_div]

/-! ## Section 8: CSS Subsystem Codes -/

/-- A CSS subsystem code is a subsystem code where gauge generators are either
    purely X-type or purely Z-type (same as CSS stabilizer codes). -/
structure CSSSubsystemCode (n mX mZ mStab : ℕ) where
  /-- X-type gauge generators -/
  xGaugeGenerators : Fin mX → GaugeOperator n
  /-- Z-type gauge generators -/
  zGaugeGenerators : Fin mZ → GaugeOperator n
  /-- Stabilizer generators -/
  stabilizerGenerators : Fin mStab → GaugeOperator n
  /-- X generators are pure X-type -/
  xGenerators_pure : ∀ i, (xGaugeGenerators i).supportZ = ∅
  /-- Z generators are pure Z-type -/
  zGenerators_pure : ∀ j, (zGaugeGenerators j).supportX = ∅
  /-- X generators commute with each other -/
  xGenerators_commute : ∀ i j, GaugeOperator.commutes (xGaugeGenerators i) (xGaugeGenerators j)
  /-- Z generators commute with each other -/
  zGenerators_commute : ∀ i j, GaugeOperator.commutes (zGaugeGenerators i) (zGaugeGenerators j)
  /-- Stabilizers commute with all X generators -/
  stab_commutes_x : ∀ k i, GaugeOperator.commutes (stabilizerGenerators k) (xGaugeGenerators i)
  /-- Stabilizers commute with all Z generators -/
  stab_commutes_z : ∀ k j, GaugeOperator.commutes (stabilizerGenerators k) (zGaugeGenerators j)
  /-- Stabilizers mutually commute -/
  stab_commute : ∀ k₁ k₂, GaugeOperator.commutes (stabilizerGenerators k₁) (stabilizerGenerators k₂)

namespace CSSSubsystemCode

variable {n mX mZ mStab : ℕ}

/-- Total number of gauge generators -/
def numGaugeGenerators (_C : CSSSubsystemCode n mX mZ mStab) : ℕ := mX + mZ

/-- X generators have empty Z support by construction -/
@[simp]
theorem xGen_supportZ_empty (C : CSSSubsystemCode n mX mZ mStab) (i : Fin mX) :
    (C.xGaugeGenerators i).supportZ = ∅ := C.xGenerators_pure i

/-- Z generators have empty X support by construction -/
@[simp]
theorem zGen_supportX_empty (C : CSSSubsystemCode n mX mZ mStab) (j : Fin mZ) :
    (C.zGaugeGenerators j).supportX = ∅ := C.zGenerators_pure j

/-- X generators are pure X-type (they commute among themselves trivially) -/
theorem xGenerators_pairwise_commute (C : CSSSubsystemCode n mX mZ mStab) (i₁ i₂ : Fin mX) :
    GaugeOperator.commutes (C.xGaugeGenerators i₁) (C.xGaugeGenerators i₂) :=
  C.xGenerators_commute i₁ i₂

/-- Z generators are pure Z-type (they commute among themselves trivially) -/
theorem zGenerators_pairwise_commute (C : CSSSubsystemCode n mX mZ mStab) (j₁ j₂ : Fin mZ) :
    GaugeOperator.commutes (C.zGaugeGenerators j₁) (C.zGaugeGenerators j₂) :=
  C.zGenerators_commute j₁ j₂

end CSSSubsystemCode

/-! ## Section 9: Helper Lemmas -/

/-- Number of qubits is preserved -/
@[simp]
theorem SubsystemCode.numQubits_eq {n mGauge mStab : ℕ} (C : SubsystemCode n mGauge mStab) :
    C.numQubits = n := rfl

/-- Number of gauge generators is mGauge -/
@[simp]
theorem SubsystemCode.numGaugeGenerators_eq {n mGauge mStab : ℕ}
    (C : SubsystemCode n mGauge mStab) :
    C.numGaugeGenerators = mGauge := rfl

/-- Number of stabilizer generators is mStab -/
@[simp]
theorem SubsystemCode.numStabilizerGenerators_eq {n mGauge mStab : ℕ}
    (C : SubsystemCode n mGauge mStab) :
    C.numStabilizerGenerators = mStab := rfl

/-- Stabilizer code converted to subsystem has zero gauge qubits -/
theorem stabilizerToSubsystem_gauge_zero {n k : ℕ} (_C : StabilizerCode n k) :
    gaugeDimExponent (n - k) (n - k) = 0 := by
  simp only [gaugeDimExponent, Nat.sub_self, Nat.zero_div]

/-- Gauge fixing preserves number of physical qubits -/
theorem GaugeFixing.numQubits_preserved {n mGauge mStab : ℕ}
    (gf : GaugeFixing n mGauge mStab) :
    gf.code.numQubits = n := rfl

/-- The edge-vertex condition is equivalent to having a cycle in the graph -/
theorem edge_vertex_condition_iff_cycle (E V : ℕ) (hV : V ≥ 1) :
    (E > V - 1) ↔ (E ≥ V) := by
  omega

/-- When gauge group equals stabilizer group, gauge dimension is zero -/
theorem gauge_equals_stabilizer_dim_zero (n mStab : ℕ) :
    gaugeDimExponent mStab mStab = 0 :=
  gauge_dim_zero_of_effectively_stabilizer (n := n)
    (SubsystemCode.mk (fun _ => GaugeOperator.identity n)
                      (fun _ => GaugeOperator.identity n)
                      (fun _ _ => GaugeOperator.identity_commutes _)
                      (fun _ _ => GaugeOperator.self_commutes _))

end QEC
